bug:
  - head-branch: ["bug/*"]

chore:
  - head-branch: ["chore/*"]

feature:
  - head-branch: ["feature/*"]

dependencies:
  - changed-files:
      - any-glob-to-any-file: ["package.json", "package-lock.json"]

documentation:
  - changed-files:
      - any-glob-to-any-file: ["README.md"]

github_actions:
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/*.yaml"]
