name: Chore
description: Allocate time to address technical debt, maintenance, or other non-feature work
title: "Chore: "
labels: chore

body:
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: A clear and concise description of the problem you are trying to solve.
      placeholder: Problem description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of the solution you are proposing.
      placeholder: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternative solutions

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide any additional details about the feature request.
      placeholder: Additional context
